<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) LOCKON CO.,LTD. All Rights Reserved.
 *
 * http://www.lockon.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Eccube\Common\EccubeConfig;
use Eccube\Doctrine\Query\Queries;
use Eccube\Entity\Company;
use Eccube\Util\StringUtil;
use Symfony\Bridge\Doctrine\RegistryInterface;
use Symfony\Component\Security\Core\Encoder\EncoderFactoryInterface;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends AbstractRepository
{
   /**
     * ClassNameRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Company::class);
    }

    /**
     * 規格一覧を取得する.
     *
     * @return array 規格の配列
     */
    public function getList()
    {
        $qb = $this->createQueryBuilder('cn');
        $company = $qb->getQuery()->getResult();

        return $company;
        // $em = $this->getEntityManager();
        // $qb = $em->createQueryBuilder()
        //             ->select('u')
        //          ->from('\Eccube\Entity\Company', 'u');

        // $q = $qb->getQuery();
        // $results = $q->execute();
        // return $results;
    }

    public function create($company)
    {
        $Company = new \Eccube\Entity\Company();

        // $em = $this->getEntityManager();
        // $em->persist($company);
        // $em->flush($company);
        return $Company;
    }

    public function update($entity)
    {
        
    }

    /**
     * 規格を削除する.
     *
     * @param company $company
     *
     */
    public function delete($company)
    {
        $em = $this->getEntityManager();
        $em->remove($company);
        $em->flush($company);
    }
}
