<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) LOCKON CO.,LTD. All Rights Reserved.
 *
 * http://www.lockon.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository;

use Doctrine\ORM\EntityRepository;
use Eccube\Doctrine\Query\Queries;
use Eccube\Common\EccubeConfig;
use Eccube\Entity\Company;
use Eccube\Util\StringUtil;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends AbstractRepository
{
    /**
     * @var Queries
     */
    protected $queries;

    /**
     * @var EntityRepository
     */
    protected $entityRepository;

    /**
     * @var EccubeConfig
     */
    protected $eccubeConfig;

    /**
     * CompamyRepository constructor.
     *
     * @param RegistryInterface $registry
     * @param Queries $queries
     * @param EccubeConfig $eccubeConfig
     */
    public function __construct(RegistryInterface $registry, Queries $queries, EccubeConfig $eccubeConfig)
    {
        parent::__construct($registry, Company::class);
        $this->queries = $queries;
        $this->eccubeConfig = $eccubeConfig;
    }

    /**
     * 規格一覧を取得する.
     *
     * @return array 規格の配列
     */
    public function getList($searchData)
    {
        
        $qb = $this->createQueryBuilder('c')
            ->select('c');

    if (isset($searchData['multi']) && StringUtil::isNotBlank($searchData['multi'])) {
        //スペース除去
        $clean_key_multi = preg_replace('/[　]+/u', '', $searchData['multi']);
        $id = preg_match('/^\d{0,10}$/', $clean_key_multi) ? $clean_key_multi : null;
        $space = $this->eccubeConfig->get('eccube_space');
        $qb
            ->andWhere('c.id LIKE :id OR CONCAT(c.name, :space) LIKE :name ')
            ->setParameter('id', '%'.$id.'%')
            ->setParameter('name', '%'.$clean_key_multi.'%')
            ->setParameter('space', $space);
        }
        // create_date
         if (!empty($searchData['create_date_start']) && $searchData['create_date_start']) {
            $qb
                ->andWhere('c.create_date >= :create_date_start')
                ->setParameter('create_date_start', $searchData['create_date_start']);
        }

        // update_date
        if (!empty($searchData['update_date_start']) && $searchData['update_date_start']) {
            $qb
                ->andWhere('c.update_date >= :update_date_start')
                ->setParameter('update_date_start', $searchData['update_date_start']);
        }
            
        $qb->addOrderBy('c.update_date', 'DESC');

        return $this->queries->customize(QueryKey::COMPANY_SEARCH, $qb, $searchData);
    }

    public function create()
    {
        $Company = new \Eccube\Entity\Company();

        // $em = $this->getEntityManager();
        // $em->persist($company);
        // $em->flush($company);
        return $Company;
    }

    public function update($entity)
    {
        
    }
    
}